#!/usr/bin/env node
/**
 * Bump the user-visible app version in all files that carry it:
 *   - package.json        (version)
 *   - app.json            (expo.version) ← source of truth for EAS builds (CNG)
 *   - android/app/build.gradle (versionName), only if the generated dir exists locally
 *
 * Usage: npm run version:bump 1.2.0
 *
 * The Android versionCode is NOT touched here — EAS manages it remotely
 * (eas.json: appVersionSource "remote" + autoIncrement) on each production build.
 */

const fs = require('fs');
const path = require('path');

const newVersion = process.argv[2];

if (!newVersion || !/^\d+\.\d+\.\d+$/.test(newVersion)) {
  console.error('Usage: npm run version:bump <major.minor.patch>  (e.g. 1.2.0)');
  process.exit(1);
}

const root = path.join(__dirname, '..');

function updateJson(relPath, update) {
  const filePath = path.join(root, relPath);
  const json = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  const oldVersion = update(json);
  fs.writeFileSync(filePath, JSON.stringify(json, null, 2) + '\n');
  console.log(`${relPath}: ${oldVersion} -> ${newVersion}`);
}

updateJson('package.json', (json) => {
  const old = json.version;
  json.version = newVersion;
  return old;
});

updateJson('app.json', (json) => {
  const old = json.expo.version;
  json.expo.version = newVersion;
  return old;
});

const gradlePath = path.join(root, 'android/app/build.gradle');
if (fs.existsSync(gradlePath)) {
  const gradle = fs.readFileSync(gradlePath, 'utf8');
  const match = gradle.match(/versionName "([^"]+)"/);
  if (!match) {
    console.error('Could not find versionName in android/app/build.gradle');
    process.exit(1);
  }
  fs.writeFileSync(gradlePath, gradle.replace(/versionName "[^"]+"/, `versionName "${newVersion}"`));
  console.log(`android/app/build.gradle: ${match[1]} -> ${newVersion}`);
} else {
  console.log('android/app/build.gradle: not present (generated by prebuild), skipped');
}

console.log('\nDone. versionCode is auto-incremented by EAS on the next production build.');
